$lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
$suspend_cmd = qs -c noctalia-shell ipc call lockScreen lock

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = $lock_cmd
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    inhibit_sleep = 120
}

listener {
    timeout = 300 # 5mins
    on-timeout = $lock_cmd
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900 # 15mins
    on-timeout = $suspend_cmd
}
