-- Custom environment variables. Loaded after hyprland/env.lua, so anything
-- set here wins.
--
-- Currently empty — kept as the designated place for machine-specific env
-- overrides. hyprland/services/create_custom_config.lua recreates this file
-- if it is ever deleted.
