# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Bar, wallpaper
exec-once = swww-daemon --format xrgb
exec-once = /usr/lib/geoclue-2.0/demos/agent & gammastep
exec-once = vicinae server

exec-once = tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"

# Clipboard: history
exec-once = wl-paste --watch clipse store &
exec-once = wl-paste --type text --watch clipse store
exec-once = wl-paste --type image --watch clipse store
exec-once = clipse -listen

# Miscs
exec-once = kdeconnect-indicator

exec-once = hyprpm reload
