# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# Side by-side monitor setup
# monitor=eDP-1,1920x1080@120,0x1080,1
# monitor=HDMI-A-1,1920x1080@60,0x0,1

# Top monitor setup
# monitor=eDP-1,1920x1080@120,0x1080,1
# monitor=HDMI-A-1,1920x1080@60,0x0,1

input {
    # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = us, ara
	#kb_options = grp:win_space_toggle
	kb_options = grp:alt_shift_toggle
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    touchpad {
		tap-to-click = true
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.9
    }
    special_fallthrough = true
    follow_mouse = 1
}
