# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, kitty -e nvim ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

##! Apps
bind = Super+Shift, V, exec, clipse-gui # Clipse Clipboard Manager
bind = Super, W, exec, __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia zen-browser # Zen Browser
bind = Super+Shift, F, exec, figma-linux # Figma
bind = Super+Shift, I, exec, XDG_CURRENT_DESKTOP="gnome" gnome-control-center # Gnome Settings

##! Window
bind = Super+Shift, Q, forcekillactive # Force Kill window
bind = Ctrl+Super, S, movetoworkspacesilent, special # Send to scratchpad
bind = Super, D, exec, pkill -SIGUSR1 wayscriber # Toggle wayscriber

##! Media
# Mouse controls
bindl = Ctrl, mouse:275, exec, playerctl previous # Previous track (side button 1)
bindl = Ctrl, mouse:276, exec, playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"` # Next track (side button 2)

# Volume key controls
bindle = Ctrl, XF86AudioRaiseVolume, exec, playerctl next # Next track (Ctrl+Vol Up)
bindle = Ctrl, XF86AudioLowerVolume, exec, playerctl previous # Previous track (Ctrl+Vol Down)
bindle = Alt, XF86AudioRaiseVolume, exec, playerctl position 2+ # Seek forward (Alt+Vol Up)
bindle = Alt, XF86AudioLowerVolume, exec, playerctl position 2- # Seek backward (Alt+Vol Down)

bind = SUPER, Up, exec, hyprctl keyword cursor:zoom_factor $(hyprctl -j getoption cursor:zoom_factor | jq -r '.float * (2 | sqrt)') # Zoom Up
bind = SUPER, Down, exec, hyprctl keyword cursor:zoom_factor $(hyprctl -j getoption cursor:zoom_factor | jq -r '[.float / (2 | sqrt), 1] | max') # Zoom Down
bind = SUPER, mouse:274, exec, hyprctl keyword cursor:zoom_factor 1 # Reset zoom
bind = SUPER CTRL, E, exec, HYPRSHOT_EDITOR=1 quickshell -c HyprQuickFrame -n
