# ######## Custom Window rules ########

# Clipboard manager
windowrule = match:title ^(Clipse GUI)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, size (monitor_w*.30) (monitor_h*.50)
windowrule = match:class ^(clipse)$, border_size 2

# Workspace assignments
windowrule = match:class ^(Postman)$, workspace 4
windowrule = match:class ^(kitty)$, no_blur off
windowrule = match:class ^(Spotify)$, workspace 0
windowrule = match:class ^(teams-for-linux)$, workspace 3

