# ######## Custom Window rules ########

# Clipboard manager
windowrule = match:title ^(Clipse GUI)$, float on
windowrule = match:title ^(Clipse GUI)$, size (monitor_w*.25) (monitor_h*.60)
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, size (monitor_w*.30) (monitor_h*.50)
windowrule = match:class ^(clipse)$, border_size 2

# Workspace assignments
windowrule = match:class ^(Postman)$, workspace 4
windowrule = match:class ^(kitty)$, no_blur off
windowrule = match:class ^(zen)$, no_blur off
windowrule = match:class ^(spotify)$, workspace 0
windowrule = match:class ^(teams-for-linux)$, workspace 3


windowrule = match:title ^(Ente Auth)$, float on
windowrule = match:title ^(Ente Auth)$, size (monitor_w*.25) (monitor_h*.60)

# # group 1
# workspace=1, monitor:eDP-2,     persistent:true
# workspace=2, monitor:HDMI-A-1,     persistent:true
# workspace=3, monitor:HDMI-A-1, persistent:true
#
# # group 2
# workspace=4, monitor:eDP-2,     persistent:true
# workspace=5, monitor:eDP-2,     persistent:true
# workspace=6, monitor:HDMI-A-1, persistent:true
#
# # group 3
# workspace=7, monitor:HDMI-A-1,     persistent:true
# workspace=8, monitor:HDMI-A-1,     persistent:true
# workspace=9, monitor:HDMI-A-1, persistent:true
# workspace=0, monitor:HDMI-A-1, persistent:true
